### ISSUE TITLE
I am trying to sanitize a string using go-sanitize package which have newline characters(\n), but I am not able to remove \n characters. 

### ISSUE THREAD

**Issue by sagar-work** [go-sanitize/sanitize#13]
I have an input string, for example:
  i.e str := "\n\n hey how are you \n\n"
I am trying to sanitize the above string using the go-sanitize package.

I have looked at the code for this package, where you have implemented space trimming in the **'string.go'** file. But according to me, you haven't implemented **trimming of newline(\n) characters**.
Can you please suggest if the above-mentioned is correct? If yes, can we extend it for trimming newline characters also?

Code of trimming space in **string.go**

   // Trim must happen before the other tags, no matter what other
   // components there are.

      if _, ok := tags["trim"]; ok {
	// Ignore value of this component, we don't care *how* to trim,
	// we just trim.
	   oldStr := field.String()
	   field.SetString(strings.Trim(oldStr, " "))
      }

Thanks!

**Comment by hscasn** [comment]
https://github.com/go-sanitize/sanitize/pull/15
