### ISSUE TITLE
Feature Request: Support custom sanitizers

### ISSUE THREAD

**Issue by shawalli** [go-sanitize/sanitize#14]
Many struct-tag packages support the ability for consuming projects to inject custom directives into their struct tags. This functionality would greatly extend the flexibility and usability of this project. As a simple example, I need the ability to ensure a string starts with an uppercase letter. I'd like to leave all of the other characters in the string as-is.

For reference, here is another struct-tag project does it: [`httpin`](https://ggicci.github.io/httpin/directives/custom)

If this idea is approved, I'm willing to contribute a PR to implement it.

**Comment by hscasn** [comment]
Sounds like a really useful feature. I'd be happy to review your implementation.
