### ISSUE TITLE
Trim tag does not seem to work

### ISSUE THREAD

**Issue by sofiadipace** [go-sanitize/sanitize#17]
I just installed this package and imported it in my file.
I tried to create a new Instance like in the example presented (s := sanitizer.New()) and I got an error.
So I just followed some suggestions and I defined the instance like this: s := sanitize.Sanitizer{}

I ran the code but the "trim method" does not return what it is supposed to return.
Can someone help me further?

```
package main

import (
	"fmt"
	"github.com/go-sanitize/sanitize"
)

type Dog struct {
    Name  string  `san:"max=5,trim,lower"`
    Breed *string `san:"def=unknown"`
}

func main() {
    d := Dog{
        Name: "Borky Borkins",
        Breed: nil,
    }

    s := sanitize.Sanitizer{}
    s.Sanitize(&d)

    fmt.Printf("Name: %s, Breed: %s", d.Name, d.Breed)
    // Name: borky, Breed: unknown
}
```

Output:
Name: **Borky Borkins,** Breed: %!s(*string=<nil>)%   <---- The trim method does not seem to work here

**Comment by sofiadipace** [comment]
fixed!

package main

import (
	"fmt"

	"github.com/go-sanitize/sanitize"
)

type Dog struct {
	Name  string  `san:"max=5,trim,lower"`
	Breed *string `san:"def=unknown"`
}

func main() {
	d := Dog{
		Name:  "Borky Borkins",
		Breed: nil,
	}

	s, err := sanitize.New()
	if err != nil {
		fmt.Println("Error creating sanitizer:", err)
		return
	}

	if err := s.Sanitize(&d); err != nil {
		fmt.Println("Error sanitizing struct:", err)
		return
	}

	fmt.Printf("Name: %s, Breed: %s", d.Name, *d.Breed)
	// Output: Name: borky, Breed: unknown
}

**Comment by mattwelke** [comment]
Thanks for catching that. README updated.
